Added picture links and links completion
TeddyDD/kakoune-wiki pull request #2
Opened 2018-08-22 18:34 UTC by ASMfreaK

Hello! Thanks for the nice repo!
Here is a new extension for the wiki!

2018-08-24 12:14 UTC, TeddyDD commented
Hi! Thanks for your contribution. I need to reviews your changes carefully since they add quite a lot of complexity. I noticed some issues:

- wiki command does not show completion
- after image expansion with `@` tag you can't go to new line with enter, you have to exit inset mode and enter it again

2018-08-24 12:18 UTC, TeddyDD requested changes
review

2018-08-24 12:18 UTC, TeddyDD commented on wiki.kak
> +    hook buffer InsertChar \n -group wiki %{
is separate hook necessary?

2018-08-24 12:18 UTC, TeddyDD commented on wiki.kak
> +-shell-candidates %{ cd $kak_opt_wiki_path; find . -type f -name '*.md' | sed -e 's/^\.\///y' }  \
what does `y` option do in sed? I coudn't find docs for this

2018-08-24 12:18 UTC, TeddyDD commented on wiki.kak
> +        echo 'completing ...'
remove this, no need to be verbose

2018-08-24 13:07 UTC, TeddyDD commented on wiki.kak
> +-shell-candidates %{ cd $kak_opt_wiki_path; find . -type f -name '*.md' | sed -e 's/^\.\///y' }  \
it seems that change breaks file completion in wiki command for me

2018-08-24 16:26 UTC, ASMfreaK commented
I'll reiterate on this. I'm sorry. I've posted it half asleep, so it is very messy. I've spotted a very disappointing typo in README.md too.

2018-08-24 17:11 UTC, TeddyDD commented
no worries, I have typos all over the place :) I really like idea of image links and completion, and it works quite well.  Actually only thing I don't like is `+` sign required for creating pages, but it shoudn't be too hard to change.

2019-01-02 09:15 UTC, TeddyDD commented
I'm integrating some features from this pr in https://github.com/TeddyDD/kakoune-wiki/tree/update-07 branch:

- [x] expand picture command
-  [x] `@!image` syntax
- [ ] completion

2021-11-22 23:11 UTC, TeddyDD commented
I'm rewriting this plugin from scratch. Closing this PR since it won't apply to new version.

2021-11-22 23:11 UTC, closed without merging